### PR TITLE
[Migration]: Transition code from old repo

### PR DESCRIPTION
**Pull request by unrahul**
- Transitioning code from clearlinux/dockerfiles to intel/stacks
- Adding a readme for the repo
- Adding dlrs - TensorFlow dockerfiles

### CODE REVIEW

**Review by Meadosc — APPROVED** [review]
LGTM

**Comment by unrahul** [comment]
@DnPlas  can we merge this?

**Review by DnPlas — APPROVED** [review]

**Review by DnPlas — CHANGES_REQUESTED** [review]
Can we add one more level to the tree?
dlrs/clearlinux/tensorflow/*

**Comment by unrahul** [comment]
@DnPlas  done!

**Review by DnPlas — CHANGES_REQUESTED** [review]
It seems like there's a duplicated tensroflow dir

**Review by DnPlas — APPROVED** [review]

**Pull request merged**
